#!/bin/bash
#
# Print the timestamp and user ID of the last dataset update
#
# When called any standard dataset argument, reports information
# for that single dataset.
#
# When called with the location of an entire HAMMERPANTS store,
# reports this information for all datasets in it. Each line
# additionally reports the path to the dataset in the store,
# in this case
#
set -e -u

source hammerpants_dsinfo
# if no HAMMERPANTS location was determined, use argument
hp=${hp_path:-$1}

if [ -n "${git_ds:-}" ]; then
  $git_ds rev-list HEAD -n 1 --format="format:%aI %aE" | tail -n1
else
  find "$hp" \
      -mindepth 3 -maxdepth 3 \
      -name objects \
      -type d \
      -execdir bash -c 'printf "$(git rev-list HEAD -n 1 --format="format:%aI %aE" | tail -n1)\t$(readlink -f .)\n"' \;
fi
